# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina"
])

languages([
  "en-US",
  "de-DE"
])

# The name of the scheme which contains the UI Tests
scheme "ParkenDDUITests"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./ParkenDD.xcworkspace"

# For more information about all available options run
# snapshot --help
